go:
    version: 1.22.4
    cgo: false
repository:
    path: github.com/eu-cdse/openstack_exporter
build:
    prefix: .
    binaries:
        - name: openstack_exporter
          path: .
    flags: -a -tags netgo
    ldflags: |
        -s
        -X {{repoPath}}/version.Version={{.Version}}
        -X {{repoPath}}/version.Revision={{.Revision}}
        -X {{repoPath}}/version.Branch={{.Branch}}
        -X {{repoPath}}/version.BuildUser={{user}}@{{host}}
        -X {{repoPath}}/version.BuildDate={{date "20060102-15:04:05"}}
tarball:
    prefix: .
    files:
        - LICENSE
crossbuild:
    platforms:
        - linux/amd64
